// Product List
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

// Product Details
export const PRODUCT_DETAIL_REQUEST='PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS='PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL='PRODUCT_DETAIL_FAIL';

// Cart
export const CART_ADD_ITEM='CART_ADD_ITEM';
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS='CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD='CART_SAVE_PAYMENT_METHOD';

// Order
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
